Encoder
ggajoch/SolderingStation pull request #3
Opened 2016-12-27 23:47 UTC by piotrva

Working encoder with sleep button & temperature change.

2016-12-28 14:21 UTC, ggajoch requested changes

2016-12-28 14:21 UTC, ggajoch commented on Firmware/targets/arm/Src/HAL.cpp
> +    encoderSetCallback(callback);
incorrect name. This is not encoder callback but rather button

2016-12-28 14:21 UTC, ggajoch commented on Firmware/targets/arm/Src/HAL.cpp
> +    return encoderGetAndReset();
name. maybe encoderGetCountAndReset()?

2016-12-28 14:21 UTC, ggajoch commented on Firmware/targets/arm/Src/HAL.cpp
> +};  // namespace Encoder
no semicolon after namespace

2016-12-28 14:21 UTC, ggajoch commented on Firmware/targets/arm/Src/encoder_hw.cpp
> +//#include "EncoderLogic.h"
commented code

2016-12-28 14:21 UTC, ggajoch commented on Firmware/targets/arm/Src/encoder_hw.cpp
> +#define DEBOUNCE_STABLE 5
extract constants to another file; preffered use constexpr static in C++
(config file have to be in C++ format because of rest of the code)

2016-12-28 14:21 UTC, ggajoch commented on Firmware/targets/arm/Src/encoder_hw.cpp
> +class LineDebounce {
extract this class to "libs" folder + unit tests for it

2016-12-28 14:21 UTC, ggajoch commented on Firmware/targets/arm/Src/encoder_hw.cpp
> +class LineDebounce {
add template parameter for debouncing constant

2016-12-28 14:21 UTC, ggajoch commented on Firmware/targets/arm/Src/encoder_hw.cpp
> +    inline LineState getState() {
remove 'inline'. In-class method is implicitly inline

2016-12-28 14:21 UTC, ggajoch commented on Firmware/targets/arm/Src/encoder_hw.cpp
> +    uint8_t times_stable;
maybe something larger; eg. uint16_t? will it be useful?

2016-12-28 14:21 UTC, ggajoch commented on Firmware/targets/arm/Src/encoder_hw.cpp
> +void encoderInit(void) {
this is .cpp file  explicit (void) in parameter unnecessary

2016-12-28 14:21 UTC, ggajoch commented on Firmware/targets/arm/Src/encoder_hw.cpp
> +LineDebounce LineP, LineN, LineB;
I know names are meaningfull right now, but make them more explicit. eg. ButtonDebouncedLine or sth?

2016-12-28 14:21 UTC, ggajoch commented on Firmware/targets/arm/Src/encoder_hw.cpp
> +        encoderCount = 0;
do I know? this will discard partially done tick, maybe use modulo?

2016-12-28 14:21 UTC, ggajoch commented on Firmware/targets/arm/Src/encoder_hw.cpp
> +        encoderCount = 0;
like encoderCount %= ENCODER_PRESC

2016-12-28 14:21 UTC, ggajoch commented on Firmware/targets/arm/Src/encoder_hw.cpp
> +            encoderCallback();
do not invoke any external callback from ISR. do it in main() loop, e.g. before next tick() - changes will not take effect until next tick()

2016-12-28 14:21 UTC, ggajoch commented on Firmware/targets/arm/Src/stm32f1xx_it.c
> +  encoderTimCallback();
maybe rename it to make it more meaningfull? like encoder10kHzTickISR()?

2016-12-28 14:27 UTC, piotrva commented on Firmware/targets/arm/Src/encoder_hw.cpp
> +            encoderCallback();
Done

2016-12-28 14:28 UTC, piotrva commented on Firmware/targets/arm/Src/stm32f1xx_it.c
> +  encoderTimCallback();
Agree with it - name changed

2016-12-28 14:29 UTC, piotrva commented on Firmware/targets/arm/Src/encoder_hw.cpp
> +void encoderInit(void) {
Done

2016-12-28 14:32 UTC, piotrva commented on Firmware/targets/arm/Src/encoder_hw.cpp
> +    uint8_t times_stable;
Can be uint32_t - it won't consume additional memory due to padding.

2016-12-28 14:49 UTC, piotrva commented on Firmware/targets/arm/Src/encoder_hw.cpp
> +    inline LineState getState() {
Done

2016-12-28 17:23 UTC, piotrva commented on Firmware/targets/arm/Src/encoder_hw.cpp
> +        encoderCount = 0;
Nope, above line may cause double tick recognisation, ie:
1. after some ISR: encoderCount = 2  (ENCODER PRESC = 4)
2. (encoderCount %= ENCODER_PRESC) == 2 -> causes returning 2 and resetting
3. complete turn after some ISR: encoderCount = 2
4. Again returning 2...

2016-12-28 17:24 UTC, piotrva commented on Firmware/targets/arm/Src/encoder_hw.cpp
> +void encoderInit(void) {
Done

2016-12-28 17:25 UTC, piotrva commented on Firmware/targets/arm/Src/encoder_hw.cpp
> +//#include "EncoderLogic.h"
Done

2016-12-28 17:27 UTC, piotrva commented on Firmware/targets/arm/Src/HAL.cpp
> +    return encoderGetAndReset();
Done

2016-12-28 17:27 UTC, piotrva commented on Firmware/targets/arm/Src/encoder_hw.cpp
> +//#include "EncoderLogic.h"
Done

2016-12-28 17:36 UTC, ggajoch commented on Firmware/targets/arm/Src/encoder_hw.cpp
> +    uint8_t times_stable;
ok, change it :)

2016-12-28 17:36 UTC, ggajoch commented on Firmware/targets/arm/SolderingStation.cfg
> +# This is an SolderingStation board with a single STM32F103C8Tx chip.
this file should be deleted

2016-12-28 17:39 UTC, ggajoch requested changes

2016-12-28 17:39 UTC, ggajoch commented on Firmware/targets/arm/Src/HAL.cpp
> +};  // namespace Encoder
unnecessary semicolon

2016-12-28 17:39 UTC, ggajoch commented on Firmware/targets/arm/Src/HAL.cpp
> +    encoderSetCallback(callback);
incorrect name. This is not encoder callback but rather button

2016-12-28 17:39 UTC, ggajoch commented on Firmware/targets/arm/Src/encoder_hw.cpp
> +#define DEBOUNCE_STABLE 5
extract constants to another file; preffered use constexpr static in C++
(config file have to be in C++ format because of rest of the code)

2016-12-28 17:39 UTC, ggajoch commented on Firmware/targets/arm/Src/encoder_hw.cpp
> +LineDebounce LineP, LineN, LineB;
I know names are meaningfull right now, but make them more explicit. eg. ButtonDebouncedLine or sth?

2016-12-28 21:56 UTC, piotrva commented on Firmware/targets/arm/Src/HAL.cpp
> +    encoderSetCallback(callback);
encoderSetButtonCallback for now. in future maybe separate button driver to other file

2016-12-28 22:00 UTC, piotrva commented on Firmware/targets/arm/Src/HAL.cpp
> +    encoderSetCallback(callback);
done

2016-12-28 22:01 UTC, piotrva commented on Firmware/targets/arm/Src/HAL.cpp
> +};  // namespace Encoder
this was added by autoformatting I suppose

2016-12-28 22:01 UTC, piotrva commented on Firmware/targets/arm/Src/encoder_hw.cpp
> +#define DEBOUNCE_STABLE 5
done - now still defines - constexpr tbd

2016-12-28 22:05 UTC, piotrva commented on Firmware/targets/arm/Src/encoder_hw.cpp
> +LineDebounce LineP, LineN, LineB;
Done

2016-12-28 22:05 UTC, piotrva commented on Firmware/targets/arm/Src/encoder_hw.cpp
> +LineDebounce LineP, LineN, LineB;
done

2016-12-28 22:34 UTC, piotrva commented on Firmware/targets/arm/Src/encoder_hw.cpp
> +class LineDebounce {
done - w/o unit tests

2016-12-28 22:34 UTC, piotrva commented on Firmware/targets/arm/Src/encoder_hw.cpp
> +class LineDebounce {
done

2016-12-28 22:39 UTC, ggajoch commented
maybe make "namespace debouncer", change class name to Line. 
Then, enum will go "outside" the class

2016-12-28 23:27 UTC, piotrva commented on Firmware/targets/arm/SolderingStation.cfg
> +# This is an SolderingStation board with a single STM32F103C8Tx chip.
Done

2016-12-29 12:36 UTC, ggajoch requested changes

2016-12-29 12:36 UTC, ggajoch commented on Firmware/targets/arm/Src/HAL.cpp
> +};  // namespace Encoder
shouldn't be. please, delete it and try - I'd take a look onto it.

2016-12-29 12:36 UTC, ggajoch commented on Firmware/libs/LineDebounce.h
> +    enum LineState { UNSTABLE, TRANSITION, STABLE };
maybe extract this enum "above" class to make it easier to access from outside (avoid having LineDebounce<ENCODER_DEBOUNCE_STABLE>::)

2016-12-29 12:36 UTC, ggajoch commented on Firmware/libs/LineDebounce.h
> +
namespace libs {

2016-12-29 12:36 UTC, ggajoch commented on Firmware/libs/LineDebounce.h
> +
dan

2016-12-29 16:04 UTC, merged